"""
Django settings for dki_backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@yj^8-)9)v75@9-2shou0%)i7)cjjchbc7i27b^6^eq==oqquf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'dki_core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'dki_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dki_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# File Upload Settings
DATA_UPLOAD_MAX_NUMBER_FILES = 10000
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500 MB

# ═══════════════════════════════════════════════════════════════════════════════
# RADIOMIC ENGINE CONFIGURATION
# Umbrales físicos configurables para diagnóstico médico
# Modificar estos valores ajusta la sensibilidad del análisis sin editar código
# ═══════════════════════════════════════════════════════════════════════════════

RADIOMIC_ENGINE = {
    # ───────────────────────────────────────────────────────────────────────────
    # TROMBOEMBOLISMO PULMONAR (TEP) - Unidades Hounsfield
    # ───────────────────────────────────────────────────────────────────────────
    'TEP': {
        'CONTRAST_BLOOD_MIN_HU': 250,
        'CONTRAST_BLOOD_MAX_HU': 500,
        'THROMBUS_MIN_HU': 30,
        'THROMBUS_MAX_HU': 90,
        'PULMONARY_ARTERY_MIN_HU': 150,
        'LUNG_PARENCHYMA_MIN_HU': -900,
        'LUNG_PARENCHYMA_MAX_HU': -500,
        'THROMBUS_KURTOSIS_THRESHOLD': 3.5,
        'MIN_LESION_SIZE_VOXELS': 20,
        'QANADLI_MAX_SCORE': 40,
    },
    
    # ───────────────────────────────────────────────────────────────────────────
    # ISQUEMIA CEREBRAL - TAC sin contraste
    # ───────────────────────────────────────────────────────────────────────────
    'ISCHEMIA': {
        'GRAY_WHITE_LOSS_THRESHOLD_HU': 20,
        'GRAY_MATTER_MIN_HU': 30,
        'GRAY_MATTER_MAX_HU': 45,
        'WHITE_MATTER_MIN_HU': 20,
        'WHITE_MATTER_MAX_HU': 30,
        'CYTOTOXIC_EDEMA_MAX_HU': 25,
        'ISCHEMIC_CORE_THRESHOLD_HU': 10,
        'MK_PENUMBRA_THRESHOLD': 1.2,
        'MK_CORE_THRESHOLD': 1.5,
    },
    
    # ───────────────────────────────────────────────────────────────────────────
    # SEGMENTACIÓN GENERAL
    # ───────────────────────────────────────────────────────────────────────────
    'SEGMENTATION': {
        'BONE_MIN_HU': 200,
        'BONE_MAX_HU': 3000,
        'SOFT_TISSUE_MIN_HU': 0,
        'SOFT_TISSUE_MAX_HU': 100,
        'AIR_MAX_HU': -500,
        'FAT_MIN_HU': -150,
        'FAT_MAX_HU': -50,
        'WATER_HU': 0,
    },
    
    # ───────────────────────────────────────────────────────────────────────────
    # PREPROCESAMIENTO - ROI y Optimización
    # ───────────────────────────────────────────────────────────────────────────
    'PREPROCESSING': {
        'THORAX_ROI_SIZE_CM': 20.0,
        'MIN_TISSUE_CONTENT_PERCENT': 10,
        'ENTROPY_MIN_VALID': 3.0,
        'ENTROPY_MAX_VALID': 9.0,
        'MIN_COMPONENT_SIZE': 1000,
    },
    
    # ───────────────────────────────────────────────────────────────────────────
    # MRI DKI - Diffusion Kurtosis Imaging
    # ───────────────────────────────────────────────────────────────────────────
    'MRI_DKI': {
        'B0_THRESHOLD': 50,
        'MAX_BVALUE': 10000,
        'NLMEANS_PATCH_RADIUS': 1,
        'NLMEANS_BLOCK_RADIUS': 5,
        'REGISTRATION_LEVEL_ITERS': [10, 10, 5],
        'REGISTRATION_SIGMAS': [3.0, 1.0, 0.0],
        'REGISTRATION_FACTORS': [4, 2, 1],
        'MK_MIN': 0,
        'MK_MAX': 3,
    },
}

# Etapas del Pipeline (para tracking de estado en frontend)
PIPELINE_STAGES = [
    'INGESTION',
    'CLASSIFICATION',
    'VALIDATION',
    'PREPROCESSING',
    'CROPPING',
    'FILTERING',
    'TENSORIAL_CALCULATION',
    'SEGMENTATION',
    'QUANTIFICATION',
    'OUTPUT',
]

