# Generated by Django 6.0 on 2026-02-07 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=64, null=True)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dicom_archive', models.FileField(upload_to='dicom_archives/')),
                ('dicom_directory', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('classification_confidence', models.FloatField(blank=True, null=True)),
                ('classification_details', models.JSONField(blank=True, null=True)),
                ('detected_modality', models.CharField(blank=True, max_length=20, null=True)),
                ('pipeline_progress', models.IntegerField(default=0)),
                ('pipeline_stage', models.CharField(default='UPLOAD', max_length=30)),
                ('modality', models.CharField(default='CT', max_length=20)),
            ],
            options={
                'db_table': 'dki_core_study',
            },
        ),
        migrations.CreateModel(
            name='ProcessingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uncertainty_sigma', models.FloatField(blank=True, null=True)),
                ('clot_count', models.IntegerField(blank=True, null=True)),
                ('contrast_quality', models.CharField(blank=True, max_length=20, null=True)),
                ('left_pa_obstruction_pct', models.FloatField(blank=True, null=True)),
                ('main_pa_obstruction_pct', models.FloatField(blank=True, null=True)),
                ('pulmonary_artery_volume', models.FloatField(blank=True, null=True)),
                ('qanadli_score', models.FloatField(blank=True, null=True)),
                ('right_pa_obstruction_pct', models.FloatField(blank=True, null=True)),
                ('tep_heatmap', models.CharField(blank=True, max_length=100, null=True)),
                ('tep_pa_mask', models.CharField(blank=True, max_length=100, null=True)),
                ('tep_thrombus_mask', models.CharField(blank=True, max_length=100, null=True)),
                ('total_clot_volume', models.FloatField(blank=True, null=True)),
                ('total_obstruction_pct', models.FloatField(blank=True, null=True)),
                ('brain_mask', models.CharField(blank=True, max_length=100, null=True)),
                ('mean_thrombus_kurtosis', models.FloatField(blank=True, null=True)),
                ('tep_kurtosis_map', models.CharField(blank=True, max_length=100, null=True)),
                ('audit_report', models.CharField(blank=True, max_length=100, null=True)),
                ('tep_roi_heatmap', models.CharField(blank=True, max_length=100, null=True)),
                ('source_volume', models.CharField(blank=True, max_length=100, null=True)),
                ('pseudocolor_map', models.CharField(blank=True, max_length=100, null=True)),
                ('tep_coherence_map', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_mpap', models.FloatField(blank=True, null=True)),
                ('primary_intervention_target', models.CharField(blank=True, max_length=64, null=True)),
                ('pvr_wood_units', models.FloatField(blank=True, null=True)),
                ('rv_impact_index', models.FloatField(blank=True, null=True)),
                ('voi_findings', models.JSONField(blank=True, null=True)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_result', to='dki_core.study')),
            ],
            options={
                'db_table': 'dki_core_processingresult',
            },
        ),
    ]
