# Generated by Django 6.0 on 2025-12-24 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, max_length=64, null=True)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dicom_archive', models.FileField(upload_to='dicom_archives/')),
                ('dicom_directory', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATING', 'Validating'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk_map', models.FileField(blank=True, null=True, upload_to='results/mk/')),
                ('fa_map', models.FileField(blank=True, null=True, upload_to='results/fa/')),
                ('md_map', models.FileField(blank=True, null=True, upload_to='results/md/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dki_core.study')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dki_core.study')),
            ],
        ),
    ]
