# Generated by Django 6.0 on 2026-01-10 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dki_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='core_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='entropy_map',
            field=models.FileField(blank=True, null=True, upload_to='results/ct_entropy/'),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='glcm_map',
            field=models.FileField(blank=True, null=True, upload_to='results/ct_glcm/'),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='heatmap',
            field=models.FileField(blank=True, null=True, upload_to='results/ct_heatmap/'),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='penumbra_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='quality_report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='results/ct_reports/'),
        ),

        migrations.AlterField(
            model_name='study',
            name='modality',
            field=models.CharField(choices=[('MRI_DKI', 'MRI - Diffusion Kurtosis Imaging'), ('CT_SMART', 'CT - Bio-Tensor SMART')], default='MRI_DKI', max_length=20),
        ),
    ]
