# Generated by Django 6.0 on 2026-01-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dki_core', '0002_processingresult_core_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingresult',
            name='clot_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='contrast_quality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='left_pa_obstruction_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='main_pa_obstruction_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='pulmonary_artery_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='qanadli_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='right_pa_obstruction_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='tep_heatmap',
            field=models.FileField(blank=True, null=True, upload_to='results/tep_heatmap/'),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='tep_pa_mask',
            field=models.FileField(blank=True, null=True, upload_to='results/tep_pa/'),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='tep_thrombus_mask',
            field=models.FileField(blank=True, null=True, upload_to='results/tep_thrombus/'),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='total_clot_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='total_obstruction_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='modality',
            field=models.CharField(choices=[('MRI_DKI', 'MRI - Diffusion Kurtosis Imaging'), ('CT_SMART', 'CT - Bio-Tensor SMART (Brain Ischemia)'), ('CT_TEP', 'CT - Pulmonary Embolism (TEP)')], default='MRI_DKI', max_length=20),
        ),
    ]
