# Generated by Django 6.0 on 2026-01-17 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dki_core', '0003_processingresult_clot_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dki_core.study')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='processingresult',
            name='quality_report_pdf',
        ),

        migrations.AddField(
            model_name='processingresult',
            name='brain_mask',
            field=models.FileField(blank=True, null=True, upload_to='results/ct_masks/'),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='mean_thrombus_kurtosis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='tep_kurtosis_map',
            field=models.FileField(blank=True, null=True, upload_to='results/tep_kurtosis/'),
        ),
        migrations.AddField(
            model_name='study',
            name='classification_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='classification_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='detected_modality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='pipeline_progress',
            field=models.IntegerField(default=0, help_text='Progreso dentro de la etapa actual (0-100)'),
        ),
        migrations.AddField(
            model_name='study',
            name='pipeline_stage',
            field=models.CharField(choices=[('INGESTION', 'Ingestion'), ('CLASSIFICATION', 'Classification'), ('VALIDATION', 'Validation'), ('PREPROCESSING', 'Preprocessing'), ('CROPPING', 'ROI Cropping'), ('FILTERING', 'Filtering'), ('TENSORIAL_CALCULATION', 'Tensorial Calculation'), ('SEGMENTATION', 'Segmentation'), ('QUANTIFICATION', 'Quantification'), ('OUTPUT', 'Output Generation'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='INGESTION', help_text='Etapa actual del pipeline de procesamiento', max_length=30),
        ),

        migrations.AlterField(
            model_name='study',
            name='modality',
            field=models.CharField(choices=[('MRI_DKI', 'MRI - Diffusion Kurtosis Imaging'), ('CT_SMART', 'CT - Bio-Tensor SMART (Brain Ischemia)'), ('CT_TEP', 'CT - Pulmonary Embolism (TEP)'), ('AUTO', 'Auto-detect from DICOM')], default='AUTO', max_length=20),
        ),
        migrations.AlterField(
            model_name='study',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('CLASSIFYING', 'Classifying'), ('VALIDATING', 'Validating'), ('PREPROCESSING', 'Preprocessing'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
    ]
