# Generated by Django 6.0 on 2026-01-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dki_core', '0004_alter_processinglog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='audit_report',
            field=models.FileField(blank=True, null=True, upload_to='results/audit_reports/'),
        ),
    ]
