# Generated by Django 6.0 on 2026-01-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dki_core', '0005_add_audit_report_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='tep_roi_heatmap',
            field=models.FileField(blank=True, null=True, upload_to='results/tep_roi/'),
        ),
    ]
