# Generated by Django 6.0 on 2026-01-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dki_core', '0006_add_tep_roi_heatmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingresult',
            name='source_volume',
            field=models.FileField(blank=True, help_text='Original volume converted to NIfTI for 3D viewer', null=True, upload_to='results/source_volume/'),
        ),
    ]
