# Generated by Django 6.0 on 2026-01-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dki_core', '0007_processingresult_source_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='pseudocolor_map',
            field=models.FileField(blank=True, null=True, upload_to='results/pseudocolor/'),
        ),
    ]
