# Generated by Django 6.0 on 2026-01-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dki_core', '0008_processingresult_pseudocolor_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='tep_coherence_map',
            field=models.FileField(blank=True, null=True, upload_to='results/tep_coherence/'),
        ),
    ]
