# Generated by Django 6.0 on 2026-02-15 20:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dki_core', '0010_add_ux_metadata_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingresult',
            name='estimated_mpap',
        ),
        migrations.RemoveField(
            model_name='processingresult',
            name='primary_intervention_target',
        ),
        migrations.RemoveField(
            model_name='processingresult',
            name='pvr_wood_units',
        ),
        migrations.RemoveField(
            model_name='processingresult',
            name='rv_impact_index',
        ),
        migrations.RemoveField(
            model_name='processingresult',
            name='voi_findings',
        ),
        migrations.AddField(
            model_name='processingresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processingresult',
            name='fa_map',
            field=models.FileField(blank=True, null=True, upload_to='results/fa/'),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='md_map',
            field=models.FileField(blank=True, null=True, upload_to='results/md/'),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='mk_map',
            field=models.FileField(blank=True, null=True, upload_to='results/mk/'),
        ),
        migrations.AlterField(
            model_name='processingresult',
            name='study',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dki_core.study'),
        ),
    ]
