# Generated by Django 6.0 on 2026-03-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dki_core', '0013_add_gt_validation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingresult',
            name='centerline_vtp',
            field=models.FileField(blank=True, help_text='VMTK centerlines with MaximumInscribedSphereRadius attribute (.vtp)', null=True, upload_to='results/meshes/centerline/'),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='pa_mesh',
            field=models.FileField(blank=True, help_text='VMTK smooth PA surface mesh (.obj) for Niivue 3D viewer', null=True, upload_to='results/meshes/pa/'),
        ),
        migrations.AddField(
            model_name='processingresult',
            name='thrombus_mesh',
            field=models.FileField(blank=True, help_text='Thrombus 3D mesh (.obj) rendered as solid red overlay in 3D viewer', null=True, upload_to='results/meshes/thrombus/'),
        ),
    ]
